tutorials/09_use_custom_engine: Add actual build&run instructions
gazebosim/gz-physics pull request #689
Opened 2024-09-16 08:24 UTC by peci1

# 🦟 Bug fix

Fixes https://github.com/gazebosim/gazebo_test_cases/issues/1428

## Summary
The tutorial included wrong instructions for building the example. This PR fixes that.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-09-16 08:31 UTC, ahcorde requested changes

2024-09-16 08:31 UTC, ahcorde commented on tutorials/09_use_custom_engine.md
> +```{.sh}
```suggestion
```bash
```

2024-09-16 08:31 UTC, ahcorde commented on tutorials/09_use_custom_engine.md
> +```{.sh}
Same with the others

2024-09-16 08:44 UTC, peci1 commented on tutorials/09_use_custom_engine.md
> +```{.sh}
Updated

2024-09-16 11:11 UTC, ahcorde approved these changes

2024-09-16 20:48 UTC, iche033 approved these changes

2024-09-16 22:17 UTC, azeey commented
Looks like there are some CI issues, but I'll go ahead and merge this since it's only updating documentation.

2024-09-16 22:18 UTC, merged

2025-10-02 20:29 UTC, scpeters commented
https://github.com/Mergifyio backport gz-physics7